Unidad 1 - Probabilidad

Actividad 2 — Carga y exploración de datos

In [5]:


import pandas as pd
import numpy as np

In [ ]:
#carga un archivo o leer
df= pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [37]:
#informacion de las primera 5 filas
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [ ]:
#ver dimensiones
df.shape

(38400, 5)

In [ ]:
#nombre de columnas
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [ ]:
#tipos de datos
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [ ]:
#resumen estadistico
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [ ]:
#cuenta el numero de valores nulos o faltantes
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [ ]:
#cantidad de entidades
df["Entity"].nunique()

256

1.¿Cuántas filas y columnas tiene el dataset? 38400 rows × 5 columns
2.¿Qué tipo de datos contiene la variable Year? int
3.¿Existen valores faltantes? Si
4.¿Cuántas entidades diferentes contiene el dataset? 256

In [32]:
df_year = df[["Entity", "Year"]]
df_year.head()

        Entity  Year
0  Afghanistan  1951
1  Afghanistan  1952
2  Afghanistan  1953
3  Afghanistan  1954
4  Afghanistan  1955

In [29]:
df_extraccion_filas = df[df["Year"] == 2020]
df_extraccion_filas.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN

In [13]:
df_2020_mx = df[(df["Year"]==2020) & (df["Entity"]=="Mexico")]
df_2020_mx.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [ ]:
#Rango de fechas desde el año que nacimos hasta el 2020
df_2005_2020_mex = df [(df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Code"] == "MEX")]
df_2005_2020_mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN

In [15]:
df_ext_EYA= df_2005_2020_mex[["Entity", "Year","Annual change in population"]]
df_ext_EYA

       Entity  Year  Annual change in population
22254  Mexico  2005                    1417373.0
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0
22258  Mexico  2009                    1625434.0
22259  Mexico  2010                    1624178.0
22260  Mexico  2011                    1619605.0
22261  Mexico  2012                    1574705.0
22262  Mexico  2013                    1525364.0
22263  Mexico  2014                    1440693.0
22264  Mexico  2015                    1288045.0
22265  Mexico  2016                    1179034.0
22266  Mexico  2017                    1148708.0
22267  Mexico  2018                    1173661.0
22268  Mexico  2019                    1189265.0
22269  Mexico  2020                    1036075.0

In [16]:
df_ext_EYA.mean(numeric_only=True)

Year                              2012.500
Annual change in population    1400307.625
dtype: float64

In [31]:
df_new = df[["Entity"]]
df_new

            Entity
0      Afghanistan
1      Afghanistan
2      Afghanistan
3      Afghanistan
4      Afghanistan
...            ...
38395     Zimbabwe
38396     Zimbabwe
38397     Zimbabwe
38398     Zimbabwe
38399     Zimbabwe

[38400 rows x 1 columns]

In [21]:
df.loc[:,["Entity", "Year"]]

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [22]:
df.iloc[:, 0:2]

            Entity Code
0      Afghanistan  AFG
1      Afghanistan  AFG
2      Afghanistan  AFG
3      Afghanistan  AFG
4      Afghanistan  AFG
...            ...  ...
38395     Zimbabwe  ZWE
38396     Zimbabwe  ZWE
38397     Zimbabwe  ZWE
38398     Zimbabwe  ZWE
38399     Zimbabwe  ZWE

[38400 rows x 2 columns]

In [23]:
df.loc[30:35]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
30,Afghanistan,AFG,1981,-1231727.0,NaN
31,Afghanistan,AFG,1982,-946206.0,NaN
32,Afghanistan,AFG,1983,-73395.0,NaN
33,Afghanistan,AFG,1984,272237.0,NaN
34,Afghanistan,AFG,1985,236633.0,NaN
35,Afghanistan,AFG,1986,-6781.0,NaN

EJERCICIOS loc y iloc

In [ ]:
#1 loc- filas: filas cuyo indice sea 10000
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [ ]:
#2. loc - columnas:  seleccional las columnas
df.loc[:,["Entity", "Year", "Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [29]:
#3. combina ambos
df.loc[10000,["Entity", "Year", "Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [28]:
# 4. loc - filtro . selecciona todos los registros de mexico al año 2020
df.loc[(df["Year"] == 2020) & (df["Entity"] == "Mexico")]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [27]:
#5. iloc - filas: selecciona primera 5 filas del df
df.iloc[0:5]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [54]:
#6. iloc - columnas: secciona todas las filas de las columnas que ocupan las posiciones 1,2 y 3
df.iloc[:, 1:4]

      Code  Year  Annual change in population
0      AFG  1951                     103163.0
1      AFG  1952                     108441.0
2      AFG  1953                     108919.0
3      AFG  1954                     111251.0
4      AFG  1955                     119027.0
...    ...   ...                          ...
38395  ZWE  2096                          NaN
38396  ZWE  2097                          NaN
38397  ZWE  2098                          NaN
38398  ZWE  2099                          NaN
38399  ZWE  2100                          NaN

[38400 rows x 3 columns]

In [11]:
#7. iloc - filas y columnas: selecciona las filas de la posicion 0 o 4 y columnas de la posicion 0 a 3
df.iloc[0:5, 0:4]

        Entity Code  Year  Annual change in population
0  Afghanistan  AFG  1951                     103163.0
1  Afghanistan  AFG  1952                     108441.0
2  Afghanistan  AFG  1953                     108919.0
3  Afghanistan  AFG  1954                     111251.0
4  Afghanistan  AFG  1955                     119027.0

Actividad 3 — Estadística descriptiva

In [13]:
#año 2005-2023 - pais que empiece M -> sera tu df
df_filtrado = df [(df["Year"] >= 2005) & (df["Year"] <= 2023) & (df["Entity"]=="Morocco")]
df_filtrado.head

<bound method NDFrame.head of         Entity Code  Year  Annual change in population  \
23454  Morocco  MAR  2005                     405124.0
23455  Morocco  MAR  2006                     413034.0
23456  Morocco  MAR  2007                     415289.0
23457  Morocco  MAR  2008                     420301.0
23458  Morocco  MAR  2009                     424010.0
23459  Morocco  MAR  2010                     436230.0
23460  Morocco  MAR  2011                     445576.0
23461  Morocco  MAR  2012                     442661.0
23462  Morocco  MAR  2013                     432327.0
23463  Morocco  MAR  2014                     417211.0
23464  Morocco  MAR  2015                     402806.0
23465  Morocco  MAR  2016                     415869.0
23466  Morocco  MAR  2017                     422936.0
23467  Morocco  MAR  2018                     393365.0
23468  Morocco  MAR  2019                     371147.0
23469  Morocco  MAR  2020                     373301.0
23470  Morocco  MAR  2021                     370235.0
23471  Morocco  MAR  2022                     374625.0
23472  Morocco  MAR  2023                     383448.0

       Annual population change (Projected)
23454                                   NaN
23455                                   NaN
23456                                   NaN
23457                                   NaN
23458                                   NaN
23459                                   NaN
23460                                   NaN
23461                                   NaN
23462                                   NaN
23463                                   NaN
23464                                   NaN
23465                                   NaN
23466                                   NaN
23467                                   NaN
23468                                   NaN
23469                                   NaN
23470                                   NaN
23471                                   NaN
23472                                   NaN  >

In [16]:
print("Media:", df_filtrado.mean(numeric_only=True) )

Media: Year                                      2014.000000
Annual change in population             408394.473684
Annual population change (Projected)              NaN
dtype: float64

In [17]:
print("Mediana:", df_filtrado.median(numeric_only=True) )

Mediana: Year                                      2014.0
Annual change in population             415289.0
Annual population change (Projected)         NaN
dtype: float64

In [18]:
print("Varianza:", df_filtrado.var(numeric_only=True) )

Varianza: Year                                    3.166667e+01
Annual change in population             6.005309e+08
Annual population change (Projected)             NaN
dtype: float64

In [19]:
print("Desviación estándar:", df_filtrado.std(numeric_only=True) )

Desviación estándar: Year                                        5.627314
Annual change in population             24505.731872
Annual population change (Projected)             NaN
dtype: float64

In [20]:
print("Mínimo:", df_filtrado.min(numeric_only=True))

Mínimo: Year                                      2005.0
Annual change in population             370235.0
Annual population change (Projected)         NaN
dtype: float64

In [21]:
print("Máximo:", df_filtrado.max(numeric_only=True) )

Máximo: Year                                      2023.0
Annual change in population             445576.0
Annual population change (Projected)         NaN
dtype: float64

Actividad 4 — Comprobación del entorno

In [39]:
import sys 

print("Python:", sys.version) 

print("Pandas:", pd.__version__) 

print("NumPy:", np.__version__)

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2